" Modeline and Notes {
" vim: set nospell foldmarker={,} foldlevel=0 foldmethod=marker:
"
" This is the personal .vimrc file of Xing Zhou
" It can be found, along with other configuration files @
"
" https://github.com/dekom/Dot_files
"
" Inspiration from spf13-vim @
" https://github.com/spf13/spf13-vim
" }

" Enviroment {
  " Basics {
    set nocompatible " Allow all vim functions
    set clipboard=unnamedplus " Linux copy-paste
  " }

  " Filetype Workarounds {
    " https://github.com/ChrisYip/Better-CSS-Syntax-for-Vim/issues/9
    autocmd BufNewFile,BufRead *.scss set filetype=css
    autocmd BufNewFile,BufRead *.sass set filetype=css
  " }

  " Load Bundles {
    if filereadable(expand("~/.vim/bundlesrc"))
      source ~/.vim/bundlesrc
    endif
  " }
" }

" General {
  set encoding=utf-8
  set background=dark         " Assume a dark background
  filetype plugin indent on   " Automatically detect file types.
  syntax on                   " syntax highlight
  set mouse=a                 " automatically enable mouse usage
  scriptencoding utf-8

  set history=10000           " increase history size
  set spell                   " turn on spellcheck
  set hidden                  " buffer is hidden instead of abandoned, can switch buffer without saving

  " Setting up the directories {
    set backup                  " create backup files

    if has('persistent_undo')
      set undofile              " save undos for files
      set undolevels=1000       " max number of undos
      set undoreload=10000      " maximum number lines to save for undo on a buffer reload
    endif

    autocmd BufWinLeave *.* silent! mkview    " make vim save view state
    autocmd BufWinEnter *.* silent! loadview  " make vim load state
  " }
" }

" Vim UI {
  " Colorscheme {
    if filereadable(expand("~/.vim/bundle/vim-colors-solarized/colors/solarized.vim"))
      let g:solarized_termcolors=256
      let g:solarized_termtrans=1
      let g:solarized_contrast="high"
      let g:solarized_visibility="high"
      color solarized           " load solarized colorscheme
    endif
  "}

  set showmode                " show the mode
  set cursorline              " highlight the cursor line

  set foldenable              " auto fold code
  set vb t_vb=                " disable visualbeep

  " Status line {
    if has('cmdline_info')
      set ruler                   " show ruler information
      set showcmd                 " show partial commands in status line
    endif

    if has('statusline')
      set laststatus=2

      set statusline=%<%f\        " filename
      set statusline+=%w%h%m%r    " options
      set statusline+=%{fugitive#statusline()} " Git status
      set statusline+=\ [%{&ff}/%Y] " filetype
      set statusline+=\ [%{getcwd()}] " current dir
      set statusline+=%=%30(%=\:%b\ %n%y%m%r%w\ (%l,%c%V)\ %p%%%)
    endif

    set fillchars+=stl:\ ,stlnc:\ 
  " }

  set backspace=indent,eol,start  " appropriate backspace
  set linespace=0                 " no space between lines
  set nu                          " show linenumbers
  set showmatch                   " show matching brackets
  set incsearch                   " search as you type
  set hlsearch                    " highlight search
  set winminheight=0              " windows can be 0 line high
  set ignorecase                  " case insensitive search
  set smartcase                   " case sensitive when uc present
  set wildmenu                    " show list instead of just completing
  set wildmode=list:longest,full  " command <Tab> completition, list matches, then longest common part, then all
  set scrolloff=3                 " minimum lines to keep above and below cursor

  set list                        " display unprintable characters
  set listchars=tab:,.,trail:.,extends:#,nbsp:. "Highlight probelmatic whitespace
  set colorcolumn=78
" }

" Formatting {
  set nowrap        " wrap long lines
  set autoindent    " indent at the same level as the previous line
  set textwidth=78

  " Tab Settings {
    set tabstop=2         " an indentation every 2 columns
    set shiftwidth=2      " use indents of 2 spaces
    set softtabstop=2     " let backspace delete indent
    set expandtab         " tabs are spaces
    set pastetoggle=<F12> " paste with correct indentation
  " }

  " Remove trailing whitespaces and ^M chars
  autocmd FileType c,cpp,java,php,javascript,python,twig,xml,yml autocmd BufWritePre <buffer> :call setline(1,map(getline(1,$),'substitute(v:val,\s\+$,,)'))
  autocmd BufNewFile,BufRead *.html.twig set filetype=html.twig

  set formatoptions=tcqronj " how vim helps with auto formatting
" }

" Key mappings {
  nnoremap Y y$     " Yank from cursor to the end of the file, to be consistent with C and D

  " Fold levels {
    nmap <leader>f0 :set foldlevel=0<CR>
    nmap <leader>f1 :set foldlevel=1<CR>
    nmap <leader>f2 :set foldlevel=2<CR>
    nmap <leader>f3 :set foldlevel=3<CR>
    nmap <leader>f4 :set foldlevel=4<CR>
    nmap <leader>f5 :set foldlevel=5<CR>
    nmap <leader>f6 :set foldlevel=6<CR>
    nmap <leader>f7 :set foldlevel=7<CR>
    nmap <leader>f8 :set foldlevel=8<CR>
    nmap <leader>f9 :set foldlevel=9<CR>
  " }

  nmap <silent> <leader>/ :let @/=''<CR>  " Remove highlights for the current term

  " Tagbar {
    nmap <leader>t :TagbarToggle<CR>      " Toggle the tagbar
  " }

  " NERDTree {
    nmap <leader>n :NERDTreeToggle<CR>    " Toggle the nerd tree
  "}

  " neocomplcache {
    let g:acp_enableAtStartup = 0             " disable autocomplpop
    let g:neocomplcache_enable_at_startup = 1 " enable neocomplcache
    let g:neocomplcache_enable_smart_case = 1 " use smartcase
    let g:neocomplcache_enable_camel_case_completion = 1  " Use camel case completion
    let g:neocomplcache_enable_underbar_completion = 1    " Use underbar completion
    let g:neocomplcache_min_syntax_length = 3 " minimum syntax keyword length
    
    imap <C-k>  <Plug>(neocomplcache_snippets_expand)
    smap <C-k>  <Plug>(neocomplcache_snippets_expand)
    inoremap <expr><C-g>  neocomplcache#undo_completion()
    inoremap <expr><C-l>  neocomplcache#complete_common_string()

    " <CR>: close popup and save indent
    inoremap <expr><CR>  neocomplcache#smart_close_popup() . "\<CR>"
    " <TAB>: completion
    inoremap <expr><TAB>  pumvisible() ? "\<C-n>" : "\<TAB>"
    " <C-h>, <BS>: close popup and delete backword char.
    inoremap <expr><C-h>  neocomplcache#smart_close_popup()."\<C-h>"
    inoremap <expr><BS>   neocomplcache#smart_close_popup()."\<C-h>"
    inoremap <expr><C-y>  neocomplcache#close_popup()
    inoremap <expr><C-e>  neocomplcache#cancel_popup()

    " Enable omni completion
    autocmd FileType css setlocal omnifunc=csscomplete#CompleteCSS
    autocmd FileType html,markdown setlocal omnifunc=htmlcomplete#CompleteTags
    autocmd FileType javascript setlocal omnifunc=javascriptcomplete#CompleteJS
    autocmd FileType python setlocal omnifunc=pythoncomplete#Complete
    autocmd FileType xml setlocal omnifunc=xmlcomplete#CompleteTags

    " Enable heavy omni completion
    if !exists('g:neocomplcache_omni_patterns')
      let g:neocomplcache_omni_patterns = {}
    endif
  " }
" }

" Plugin Configurations {
    let g:indent_guides_enable_on_vim_startup = 1 " Indent Guide me please
" }
