[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*

# Path to your oh-my-zsh configuration.
ZSH=$HOME/Dot_files/zsh/oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="dekom"

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git archlinux bundler ruby gem node python rails3 rvm bundler heroku npm vi-mode)

setopt hist_ignore_all_dups
setopt hist_ignore_space
setopt interactive_comments
setopt no_clobber
source $ZSH/oh-my-zsh.sh

# Customizations
EDITOR='$(which vim)'

PATH=$HOME/local:$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting

# Aliases
alias ls='ls -p'
alias ll='ls -lp'
alias la='ls -lpA'
alias grep='grep --color=always'

# For Openbox auto loading ssh-agent
eval $(ssh-agent) &> /dev/null

# Customize to your needs...
#export PATH=/home/xing/.rvm/gems/ruby-1.9.3-p194/bin:/home/xing/.rvm/gems/ruby-1.9.3-p194@global/bin:/home/xing/.rvm/rubies/ruby-1.9.3-p194/bin:/home/xing/.rvm/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/xing/.rvm/bin
# eval "$(hub alias -s)"

# 256 Colors
case "$TERM" in
  xterm*) TERM=xterm-256color
esac

# Wordnik API key
export WORDNIK_API=d25b766254dd7337441237e86ca0f9460f6037ff7432ae240
